services:
  db:
    image: postgres:17.7-alpine3.23
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data